fix over-flattening by List.flatten in Chunk.map_parallel
seantanly/elixir-paratize pull request #5
Opened 2017-08-11 01:32 UTC by radu

List.flatten over flattens array, making parallel_map not work as a replacement for regular map with deeply nested array.

2017-08-11 05:19 UTC, seantanly requested changes
Thanks for this bugfix PR! 

I have a few ideas regarding the test and the code fix.

For `chunk.ex`, we could use `Enum.reduce` which should be `List.foldl` under the hood, which is tail-recursive compared to `List.foldr`.

For the test, I'm favoring modifying the original test to have inside the expected result, nested list elements. For example, a `deep_multipler_2`.

I realized the original tests usage of MapSet isn't clear, thus in this PR there are usages of MapSet which isn't the intended purpose. The intention is to keep track / verify all the input arguments did get added into the agent, although not in any specific order because the parallelized execution can be in any order.

Would you like to take a stab at changing the PR, or should I go ahead with putting up a bugfix?

2017-08-11 17:04 UTC, radu commented
Hi Sean, sure I'll try to make the requested changes to the PR!

On Thu, Aug 10, 2017 at 10:19 PM, Sean Tan <notifications@github.com> wrote:

> *@seantanly* requested changes on this pull request.
>
> Thanks for this bugfix PR!
>
> I have a few ideas regarding the test and the code fix.
>
> For chunk.ex, we could use Enum.reduce which should be List.foldl under
> the hood, which is tail-recursive compared to List.foldr.
>
> For the test, I'm favoring modifying the original test to have inside the
> expected result, nested list elements. For example, a deep_multipler_2.
>
> I realized the original tests usage of MapSet isn't clear, thus in this PR
> there are usages of MapSet which isn't the intended purpose. The intention
> is to keep track / verify all the input arguments did get added into the
> agent, although not in any specific order because the parallelized
> execution can be in any order.
>
> Would you like to take a stab at changing the PR, or should I go ahead
> with putting up a bugfix?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/seantanly/elixir-paratize/pull/5#pullrequestreview-55718325>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC1a1QikkAikaXBs6lA6YkrTSL7k70Gks5sW-RlgaJpZM4O0KVG>
> .
>

2017-08-19 03:07 UTC, seantanly commented
Hi @radu, I would like to close this by this week, are you able to submit the PR changes by then?

2017-08-19 04:08 UTC, radu commented
HI Sean,  wasn't 100% sure what you meant with the deep_multiply for the test.  See the revised changeset, happy to revise again if you can point me in the right direction, also feel free to take over if that's easier.

2017-08-19 17:31 UTC, seantanly approved these changes
Thanks for putting up the revised PR! 

I have made some changes to the tests using a `deep_multiply_by_two` function as the `worker_func`. Also I have made the `Enum.reduce` statement variables more descriptive. If you're ok with the changes to the PR, I'll merge it. :)

2017-08-19 17:31 UTC, seantanly commented on lib/paratize/chunk.ex
> +    |> Enum.reduce(fn a,b -> b ++ a end)
Have a more descriptive variable name with spacing,

```
    |> Enum.reduce(fn result, acc -> acc ++ result end)
```

2017-08-19 17:40 UTC, radu commented
Of course, now I see what you meant about the test.
Thanks for fixing!

On Sat, Aug 19, 2017, 10:31 AM Sean Tan <notifications@github.com> wrote:

> *@seantanly* approved this pull request.
>
> Thanks for putting up the revised PR!
>
> I have made some changes to the tests using a deep_multiply_by_two
> function as the worker_func. Also I have made the Enum.reduce statement
> variables more descriptive. If you're ok with the changes to the PR, I'll
> merge it. :)
> ------------------------------
>
> In lib/paratize/chunk.ex
> <https://github.com/seantanly/elixir-paratize/pull/5#discussion_r134096080>
> :
>
> > @@ -31,7 +31,7 @@ defmodule Paratize.Chunk do
>        |> Enum.map(&task_async(&1))
>        |> Enum.map(&Task.await(&1, task_options.timeout))
>      end)
> -    |> List.foldr([], fn a,b -> a ++ b end)
> +    |> Enum.reduce(fn a,b -> b ++ a end)
>
> Have a more descriptive variable name with spacing,
>
>     |> Enum.reduce(fn result, acc -> acc ++ result end)
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/seantanly/elixir-paratize/pull/5#pullrequestreview-57354302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC1a0jTOyCnTna-dS96vh4-PTtY7YTSks5sZxv4gaJpZM4O0KVG>
> .
>

2017-08-19 17:46 UTC, merged